[2025-05-12T08:05:58.288+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transformation_pipeline.transform_data manual__2025-05-12T08:00:28.965047+00:00 [queued]>
[2025-05-12T08:05:58.337+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transformation_pipeline.transform_data manual__2025-05-12T08:00:28.965047+00:00 [queued]>
[2025-05-12T08:05:58.339+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-05-12T08:05:58.437+0000] {taskinstance.py:1380} INFO - Executing <Task(DockerOperator): transform_data> on 2025-05-12 08:00:28.965047+00:00
[2025-05-12T08:05:58.452+0000] {standard_task_runner.py:57} INFO - Started process 54 to run task
[2025-05-12T08:05:58.472+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_transformation_pipeline', 'transform_data', 'manual__2025-05-12T08:00:28.965047+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmp09k8iucc']
[2025-05-12T08:05:58.478+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask transform_data
[2025-05-12T08:05:58.511+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task transform_data (invalid interpolation syntax in 'dag_id={{ ti.dag_id }}/run_id={{ ti.run_id }}/task_id={{ ti.task_id }}/{% if ti.map_index >= 0 %}map_index={{ ti.map_index }}/{% endif %}attempt={{ try_number }}.log' at position 72; 54)
[2025-05-12T08:05:58.527+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-12T08:05:58.579+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
